//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosedGroupes
    {
        public int team_id { get; set; }
        public int name { get; set; }
        public string day { get; set; }
        public Nullable<int> trainer_id { get; set; }
        public string gender { get; set; }
        public Nullable<int> actual_capacity { get; set; }
        public string status { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual FitnessLessons FitnessLessons { get; set; }
        public virtual FitnessTrainers FitnessTrainers { get; set; }
    }
}
