//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitnessLessons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FitnessLessons()
        {
            this.Presence = new HashSet<Presence>();
        }
    
        public int lesson_id { get; set; }
        public string name { get; set; }
        public string day { get; set; }
        public System.TimeSpan time { get; set; }
        public int trainer_id { get; set; }
        public Nullable<int> quota_training { get; set; }
    
        public virtual FitnessTrainers FitnessTrainers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presence> Presence { get; set; }
    }
}
