//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public int customer_id { get; set; }
        public int sub_id { get; set; }
        public string status { get; set; }
        public Nullable<int> training_id { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual SubscriptionsTypes SubscriptionsTypes { get; set; }
    }
}
