//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMesseges
    {
        public int Messege_id { get; set; }
        public string Messege_Content { get; set; }
        public System.DateTime Creation_date { get; set; }
        public System.DateTime deletion_date { get; set; }
    }
}
